import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, TabStopType, TabStopPosition, UnderlineType } from 'docx';
import { GeneratedBook, PageSize } from '../types';
import { ASHVORA_LABEL } from '../constants';

export async function generateDocxBlob(book: GeneratedBook, addAshvoraLabel: boolean, pageSize: PageSize): Promise<Blob> {
  const doc = new Document({
    sections: [],
    // Default properties for the document
    creator: 'ASHVORA Book Engine',
    description: `Book generated by ASHVORA: ${book.title}`,
    title: book.title,
    styles: {
      default: {
        document: {
          run: {
            font: 'Garamond', // KDP preferred font
            size: 24, // 12pt
          },
          paragraph: {
            alignment: AlignmentType.JUSTIFIED,
            spacing: {
              line: 360, // 1.5 line spacing (1pt = 20 twips, so 1.5 * 12pt * 20 twips/pt = 360)
            },
          },
        },
      },
      paragraphStyles: [
        {
          id: 'AshvoraLabel',
          name: 'Ashvora Label',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: {
            size: 18, // 9pt
            color: '#888888',
          },
          paragraph: {
            alignment: AlignmentType.CENTER,
            spacing: {
              before: 200, // Some space before
            },
          },
        },
        {
          id: 'ChapterTitle',
          name: 'Chapter Title',
          basedOn: 'Heading1',
          next: 'Normal',
          quickFormat: true,
          run: {
            font: 'Garamond',
            size: 48, // 24pt
            bold: true,
          },
          paragraph: {
            alignment: AlignmentType.CENTER,
            spacing: {
              before: 1000, // Large space before chapter title
              after: 500,  // Space after chapter title
            },
            pageBreakBefore: true, // New page for each chapter
          },
        },
        {
          id: 'Subtitle',
          name: 'Subtitle',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: {
            font: 'Garamond',
            size: 32, // 16pt
            bold: false,
          },
          paragraph: {
            alignment: AlignmentType.CENTER,
            spacing: {
              after: 200,
            },
          },
        },
        {
          id: 'Metadata',
          name: 'Metadata',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: {
            font: 'Garamond',
            size: 20, // 10pt
            color: '#666666',
          },
          paragraph: {
            alignment: AlignmentType.CENTER,
            spacing: {
              after: 100,
            },
          },
        },
        {
          id: 'TOCHeading',
          name: 'TOC Heading',
          basedOn: 'Heading1',
          next: 'Normal',
          quickFormat: true,
          run: {
            font: 'Garamond',
            size: 48, // 24pt
            bold: true,
          },
          paragraph: {
            alignment: AlignmentType.CENTER,
            spacing: {
              before: 1000,
              after: 500,
            },
            pageBreakBefore: true,
          },
        },
        {
          id: 'TOCEntry',
          name: 'TOC Entry',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: {
            font: 'Garamond',
            size: 24, // 12pt
          },
          paragraph: {
            alignment: AlignmentType.LEFT,
            spacing: {
              after: 100,
            },
            tabStops: [
              {
                type: TabStopType.RIGHT,
                position: TabStopPosition.MAX,
              },
            ],
          },
        },
      ],
    },
  });

  // Convert markdown to paragraphs
  const markdownToParagraphs = (markdownText: string) => {
    const paragraphs: Paragraph[] = [];
    // Replace Markdown headings with bold text, handle basic lists/line breaks
    const lines = markdownText.split('\n');
    lines.forEach(line => {
      line = line.trim();
      if (line.startsWith('### ')) {
        paragraphs.push(new Paragraph({
          children: [new TextRun({ text: line.substring(4), bold: true })],
          spacing: { before: 100, after: 100 },
          alignment: AlignmentType.LEFT,
        }));
      } else if (line.startsWith('## ')) {
        paragraphs.push(new Paragraph({
          children: [new TextRun({ text: line.substring(3), bold: true })],
          spacing: { before: 150, after: 150 },
          alignment: AlignmentType.LEFT,
        }));
      } else if (line.startsWith('* ') || line.startsWith('- ')) {
        paragraphs.push(new Paragraph({
          children: [new TextRun({ text: `• ${line.substring(2)}` })],
          indent: { left: 400 }, // Simulate list indent
          alignment: AlignmentType.LEFT,
          spacing: { after: 50 },
        }));
      } else if (line) { // Add non-empty lines as regular paragraphs
        // Basic markdown bold/italic
        let processedLine = line.replace(/\*\*(.*?)\*\*/g, '@@BOLDSTART@@$1@@BOLDEND@@');
        processedLine = processedLine.replace(/\*(.*?)\*/g, '@@ITALICSTART@@$1@@ITALICEND@@');

        const children: TextRun[] = [];
        const parts = processedLine.split(/(@@BOLDSTART@@|@@BOLDEND@@|@@ITALICSTART@@|@@ITALICEND@@)/);

        let isBold = false;
        let isItalic = false;

        parts.forEach(part => {
          switch (part) {
            case '@@BOLDSTART@@':
              isBold = true;
              break;
            case '@@BOLDEND@@':
              isBold = false;
              break;
            case '@@ITALICSTART@@':
              isItalic = true;
              break;
            case '@@ITALICEND@@':
              isItalic = false;
              break;
            default:
              if (part) {
                children.push(new TextRun({ text: part, bold: isBold, italics: isItalic }));
              }
              break;
          }
        });

        paragraphs.push(new Paragraph({
          children: children.length > 0 ? children : [new TextRun({ text: line })],
          spacing: { after: 100 },
          alignment: AlignmentType.JUSTIFIED,
        }));
      } else {
        // Add an empty paragraph for line breaks
        paragraphs.push(new Paragraph({ text: '' }));
      }
    });
    return paragraphs;
  };


  // Front Matter Section (Cover, Copyright, Disclaimer, Author Intro)
  const frontMatterContent: Paragraph[] = [
    new Paragraph({
      children: [
        new TextRun({ text: book.title, break: 5 }), // Title on a new line, some breaks for spacing
      ],
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { before: 2000, after: 1000 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'By' }),
        new TextRun({ text: book.authorName, break: 1 }),
      ],
      style: 'Subtitle',
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `A book on ${book.topic}`, break: 2 }),
      ],
      style: 'Metadata',
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `(${book.writingStyle} style, ${book.language})`, break: 1 }),
      ],
      style: 'Metadata',
      spacing: { after: 1000 },
    }),
  ];

  if (book.copyrightPage) {
    frontMatterContent.push(new Paragraph({ text: '', pageBreakBefore: true })); // New page
    frontMatterContent.push(new Paragraph({ children: [new TextRun({ text: 'Copyright Page' })], alignment: AlignmentType.CENTER, spacing: { after: 200 } }));
    frontMatterContent.push(...markdownToParagraphs(book.copyrightPage));
  }

  if (book.disclaimerPage) {
    frontMatterContent.push(new Paragraph({ text: '', pageBreakBefore: true })); // New page
    frontMatterContent.push(new Paragraph({ children: [new TextRun({ text: 'Disclaimer' })], alignment: AlignmentType.CENTER, spacing: { after: 200 } }));
    frontMatterContent.push(...markdownToParagraphs(book.disclaimerPage));
  }

  if (book.authorIntroduction) {
    frontMatterContent.push(new Paragraph({ text: '', pageBreakBefore: true })); // New page
    frontMatterContent.push(new Paragraph({ children: [new TextRun({ text: 'About the Author' })], alignment: AlignmentType.CENTER, spacing: { after: 200 } }));
    frontMatterContent.push(...markdownToParagraphs(book.authorIntroduction));
  }

  doc.addSection({
    children: frontMatterContent,
  });

  // Table of Contents Section
  if (book.tableOfContents && book.tableOfContents.length > 0) {
    const tocSection: Paragraph[] = [
      new Paragraph({ text: '', pageBreakBefore: true }),
      new Paragraph({
        children: [new TextRun({ text: 'Table of Contents' })],
        style: 'TOCHeading',
      }),
    ];
    book.tableOfContents.forEach(chapter => {
      tocSection.push(new Paragraph({
        children: [
          new TextRun({ text: `Chapter ${chapter.id}: ${chapter.title}` }),
          new TextRun({ text: '\t' }), // Tab for page number alignment
          new TextRun({ text: '...' }), // Placeholder for page numbers
        ],
        style: 'TOCEntry',
      }));
    });
    doc.addSection({ children: tocSection });
  }

  // Chapters Section
  book.chapters.forEach(chapter => {
    doc.addSection({
      children: [
        new Paragraph({
          children: [new TextRun({ text: `Chapter ${chapter.id}: ${chapter.title}` })],
          style: 'ChapterTitle',
        }),
        ...markdownToParagraphs(chapter.content),
      ],
    });
  });

  // Ending Page Section
  const endingSection: Paragraph[] = [
    new Paragraph({ text: '', pageBreakBefore: true }), // New page for ending
    new Paragraph({
      children: [new TextRun({ text: 'Thank You' })],
      style: 'ChapterTitle', // Use ChapterTitle style for prominent heading
    }),
    ...markdownToParagraphs(book.endingPage),
  ];

  if (addAshvoraLabel) {
    endingSection.push(new Paragraph({
      children: [new TextRun({ text: ASHVORA_LABEL })],
      style: 'AshvoraLabel',
    }));
  }
  doc.addSection({ children: endingSection });


  const blob = await Packer.toBlob(doc);
  return blob;
}
